### ISSUE TITLE
fatal error: Don't know how to read Double

### ISSUE THREAD

**Issue by timburgess** [aleph7/HDF5Kit#14] opened 2015-11-27 03:30 UTC
I'm wondering if you guys have any ideas/suggestions about this. I am running a pretty simple piece of read code to extract from a dataset with just four Doubles in it, namely:
<pre>
guard let file = File.open(path, mode: .ReadOnly) else {
    fatalError("Failed to open \(path)")
}
guard let mmmDS = file.openDataset("mmm", type: Double.self) else {
    fatalError("Failed to open MMM node")
}
let mmm = mmmDS.read() as! [Double]
</pre>
Other than setting up some globals, this is all the code does. On running this, Xcode 7.1.1 on OS X 10.10.5 crashes on me. If I run from the command-line, I see:
<pre>
fatal error: Don't know how to read Double: file /Users/tim/work/carthage-builds/Carthage/Checkouts/HDF5Kit/Source/Dataset.swift, line 98
Illegal instruction: 4
</pre>
It seems the the Element.self == Double check is failing somehow. If I put the code into an HDF5Kit test, it works fine. I know the HDF5 is good. I can read it without problem using NumPy and it works in the test.

I suspect it is something to do with how I am building or adding the framework. I'm building HDF5Kit with Carthage. Only difference from master is that I have 'contains embedded swift code' = on, as without this the executable can't find the Swift libraries. I also use <code>install_name_tool -change ...</code> to avoid <code>rpath</code> issues by just using an absolute path:
<pre>
otool -L LSDAlgo
LSDAlgo:
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1252.0.0)
	/Users/tim/work/carthage-builds/Carthage/Build/Mac/HDF5Kit.framework/Versions/A/HDF5Kit (compatibility version 1.0.0, current version 1.0.0)
	/Users/tim/work/carthage-builds/Carthage/Build/Mac/Upsurge.framework/Versions/A/Upsurge (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1253.0.0)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 600.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
</pre>

it would be good to know a way to use HDF5Kit which avoids this hard crash issue and I'd value any thoughts.

**Comment by aleph7** [comment] 2015-11-27 05:18
Are you working on a OS X app? We ran into this same problem and I suspect the warnings you get when you launch are the root cause: 
```Class SwiftObject is implemented in both .../libswiftCore.dylib and .../MyApp. One of the two will be used. Which one is undefined.
```

Looks like it's loading two versions of the swift standard lib. The only way to resolve it was to use `Dataset.select()` and `readDouble()` instead of the subscript helpers. At least until they fix these Swift issues.

**Comment by timburgess** [comment] 2015-11-27 21:11
Thanks. Yes, it's an OS X command-line app. From what you say, it seems like avoiding swiftcore references means avoiding the two version loading issues. I have tried a few alternative ideas but unfortunately none successful. I have also hit <code>http://www.openradar.me/23551273</code> which is what is causing the Xcode crashes.

We should probably keep this issue open until there's a resolution for the double library loading.

**Comment by aleph7** [comment] 2015-12-10 19:20
This commit should fix this: https://github.com/aleph7/HDF5Kit/commit/954561f6f5fc1653e103c5621b3d7b54e99aa139

Also let me know what you think of that new approach.

**Comment by timburgess** [comment] 2015-12-10 23:41
I've had the `swift-build` branch working fine on OS X with the Swift 2.2-dev snapshot that Apple released. The only slight quirk is that there is a `import CHDF5` required but that's no biggie.
Were you planning on merging that branch into `master` or bringing these changes to the build branch?

**Comment by aleph7** [comment] 2015-12-11 00:10
I haven't figured out hot to support iOS from swift-build, so I'll leave that in a branch until that's resolved. Merged latest changes into swift-build.

**Comment by timburgess** [comment] 2015-12-11 01:53
The changes are an improvement I think to the prior methods and it all builds and works for me on swift-2.2-dev.

 `let dataset = file.openFloatDataset(nodeName)` is better than `let dataset = file.openDataset(nodeName, type: Float.self)` and of course eliminates the cast required from `Any` to `[Float]` on the dataset read (which is a good thing!). The ultimate ideal of course would be just `let ds = file.openDataset(nodeName)` or even better `let ds = file["nodeName"]`. IMO the latter enforces the concept that an HDF5 file is essentially a dictionary containing datasets.

With swift-2.2-dev, `data.read()` now produces an `..is not marked with try` issue but that doesn't concern me as I think that we should point people towards using subscript access rather than calling `data.read()`. So it would be nice to have support for `let foo = dataset[]` rather than `let foo = dataset[0..]`

My experience with scientist/progammers is that they know what the HDF5 names are that they want and they have a sense of what the data type is, and most of the time, they just want to get all the data in memory.

There is a long term issue with supporting complex HDF5 types i.e. tuples containing strings and decimals but IMHO those datasets are pretty few and far between.

Lastly, this all works for me so I have no problem with closing the issue.

**Comment by aleph7** [comment] 2015-12-11 02:16
I added `throws` because I think it makes more sense than silently failing. `subscript` doesn't support that but I think it's good to have a way of not having to deal with the throws. I agree with reading via `dataset[]`, I'll add that.

:+1:

**Closed by aleph7** 2015-12-11 02:16 UTC
Labels: s3: awaiting validation, t2: discussion
